"""initial schema

Revision ID: ccea83082431
Revises: 
Create Date: 2026-08-26 00:39:37.365462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccea83082431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required for gen_random_uuid() used as the server-side default for all
    # primary keys. Already enabled by hand on the dev/test databases, but a
    # fresh database (e.g. one created by Docker Compose) will need this.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_mapping',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('target_kind', sa.Enum('invoice', 'payment', name='source_mapping_target_kind'), nullable=False),
    sa.Column('column_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_mapping')),
    sa.UniqueConstraint('source_name', name=op.f('uq_source_mapping_source_name'))
    )
    op.create_table('upload_batch',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('invoice_pdf', 'invoice_csv', 'bank_csv', name='upload_batch_kind'), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='upload_batch_status'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('source_mapping_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_mapping_id'], ['source_mapping.id'], name=op.f('fk_upload_batch_source_mapping_id_source_mapping')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_batch'))
    )
    op.create_index(op.f('ix_upload_batch_source_mapping_id'), 'upload_batch', ['source_mapping_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('upload_batch_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('raw_reference_text', sa.Text(), nullable=True),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('unmatched', 'matched', 'exception', name='invoice_status'), server_default=sa.text("'unmatched'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], name=op.f('fk_invoice_upload_batch_id_upload_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    op.create_index(op.f('ix_invoice_upload_batch_id'), 'invoice', ['upload_batch_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('upload_batch_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('counterparty', sa.Text(), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('unmatched', 'matched', 'exception', name='payment_status'), server_default=sa.text("'unmatched'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], name=op.f('fk_payment_upload_batch_id_upload_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index(op.f('ix_payment_upload_batch_id'), 'payment', ['upload_batch_id'], unique=False)
    op.create_table('exception',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('no_candidate', 'ambiguous_multiple_candidates', 'below_threshold', 'possible_split_payment', 'rejected_by_reviewer', 'amount_mismatch_only', name='exception_reason'), nullable=False),
    sa.Column('candidate_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='exception_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_exception_invoice_id_invoice')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_exception_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception'))
    )
    op.create_index(op.f('ix_exception_invoice_id'), 'exception', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_exception_payment_id'), 'exception', ['payment_id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('date_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reference_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('match_status', sa.Enum('suggested', 'accepted', 'rejected', name='match_status'), nullable=False),
    sa.Column('suggested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_match_invoice_id_invoice')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_match_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_match_invoice_id')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_match_payment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: pgcrypto is intentionally left enabled on downgrade — it is a
    # database-wide extension, not something owned exclusively by this
    # migration, so dropping it here would be unsafe.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_index(op.f('ix_exception_payment_id'), table_name='exception')
    op.drop_index(op.f('ix_exception_invoice_id'), table_name='exception')
    op.drop_table('exception')
    op.drop_index(op.f('ix_payment_upload_batch_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_invoice_upload_batch_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_upload_batch_source_mapping_id'), table_name='upload_batch')
    op.drop_table('upload_batch')
    op.drop_table('source_mapping')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for Postgres ENUMs on table drop,
    # so the enum types created implicitly by the CREATE TABLE statements
    # above must be dropped by hand for downgrade to be a clean, full
    # reversal (verified: they are left behind otherwise).
    for enum_name in (
        "match_status",
        "exception_status",
        "exception_reason",
        "payment_status",
        "invoice_status",
        "upload_batch_status",
        "upload_batch_kind",
        "source_mapping_target_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
